#!/bin/sh

# Installs pngquant.

mkdir -p /build/pngquant
git clone -b "$PNGQUANT_VERSION" --single-branch --depth 1 --recursive https://github.com/pornel/pngquant.git /build/pngquant
cd /build/pngquant ; ./configure --prefix=/usr
make -C /build/pngquant
make -C /build/pngquant install

